# Generated by Django 3.0.2 on 2020-01-30 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(max_length=250, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('shedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termins.Shedule')),
            ],
        ),
    ]
